/**
 * workers-scaffold.ts — generate a deployable CF Workers + Static Assets project.
 *
 * Based on nanoclaw/wrangler.toml (the reference Workers config).
 * Produces wrangler.toml, src/index.ts, and .env.example for a minimal agent worker.
 * Used by `oneie init` and returned by `/api/agents/deploy`.
 */

export interface ScaffoldOpts {
  /** GATEWAY_URL default is api.one.ie */
  gatewayUrl?: string
  /** Include D1 database binding (needed for conversation storage) */
  withD1?: boolean
  /** Include KV namespace binding (needed for pheromone cache) */
  withKv?: boolean
}

export interface ScaffoldFiles {
  'wrangler.toml': string
  'src/index.ts': string
  '.env.example': string
}

/**
 * Generate all scaffold file contents for a new CF Workers + Static Assets agent project.
 * Returns a map of relative file paths → file content strings.
 */
export function generateWorkersScaffold(name: string, opts: ScaffoldOpts = {}): ScaffoldFiles {
  const { gatewayUrl = 'https://api.one.ie', withD1 = true, withKv = true } = opts
  const slug = name.toLowerCase().replace(/[^a-z0-9-]/g, '-')

  const d1Section = withD1
    ? `\n[[d1_databases]]\nbinding = "DB"\ndatabase_name = "${slug}"\ndatabase_id = "YOUR_D1_DATABASE_ID"\n`
    : ''

  const kvSection = withKv
    ? `\n[[kv_namespaces]]\nbinding = "KV"\nid = "YOUR_KV_NAMESPACE_ID"\n`
    : ''

  const wranglerToml = `name = "${slug}"
main = "src/index.ts"
workers_dev = true
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
GATEWAY_URL = "${gatewayUrl}"
${d1Section}${kvSection}
# Secrets (set via: wrangler secret put SECRET_NAME)
# OPENROUTER_API_KEY  — required for LLM calls
# ONE_API_KEY         — optional; set to connect to the ONE substrate
# TELEGRAM_TOKEN      — optional; set to enable Telegram bot
`

  const indexTs = `/**
 * ${name} — CF Workers agent scaffold
 * Generated by oneie init (platform-baas Cycle 3)
 *
 * Layer 0 (standalone): runs with just OPENROUTER_API_KEY
 * Layer 1 (connected):  set ONE_API_KEY to join the substrate
 */

export interface Env {
  GATEWAY_URL: string
  OPENROUTER_API_KEY?: string
  ONE_API_KEY?: string
  TELEGRAM_TOKEN?: string
  DB?: D1Database
  KV?: KVNamespace
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url)

    if (url.pathname === '/health') {
      return Response.json({ ok: true, agent: '${slug}', ts: Date.now() })
    }

    if (url.pathname === '/webhook/telegram' && request.method === 'POST') {
      const update = await request.json() as { message?: { text?: string; chat?: { id?: number } } }
      const text = update.message?.text ?? ''
      const chatId = update.message?.chat?.id
      if (!chatId || !env.TELEGRAM_TOKEN) return new Response('ok')

      const reply = await chat(text, env)
      await sendTelegram(chatId, reply, env.TELEGRAM_TOKEN)
      return new Response('ok')
    }

    return new Response('${name} agent — send signals via POST /webhook/telegram', { status: 200 })
  },
}

async function chat(text: string, env: Env): Promise<string> {
  if (!env.OPENROUTER_API_KEY) return 'LLM not configured — set OPENROUTER_API_KEY'
  const res = await fetch('https://openrouter.ai/api/v1/chat/completions', {
    method: 'POST',
    headers: { Authorization: \`Bearer \${env.OPENROUTER_API_KEY}\`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: 'meta-llama/llama-4-maverick',
      messages: [{ role: 'user', content: text }],
    }),
  })
  const data = await res.json() as { choices?: { message?: { content?: string } }[] }
  return data.choices?.[0]?.message?.content ?? 'No response'
}

async function sendTelegram(chatId: number, text: string, token: string): Promise<void> {
  await fetch(\`https://api.telegram.org/bot\${token}/sendMessage\`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ chat_id: chatId, text }),
  })
}
`

  const envExample = `# ${name} — CF Workers agent
# Layer 0 (standalone) — no ONE account needed
OPENROUTER_API_KEY=sk-or-...

# Layer 1 (connected) — set to join the ONE substrate
# ONE_API_KEY=one_...

# Layer 2 (chain) — set for Sui wallet + escrow
# SUI_SEED=...

# Optional: Telegram bot
# TELEGRAM_TOKEN=...

# Injected by wrangler at deploy time — do not set manually:
# GATEWAY_URL=https://api.one.ie
`

  return { 'wrangler.toml': wranglerToml, 'src/index.ts': indexTs, '.env.example': envExample }
}
