import type { Model } from './types'

export const DEFAULT_MODEL = 'meta-llama/llama-4-maverick'

export const POPULAR_MODELS: Model[] = [
  // Default model — server-configured OpenRouter key, 1M context, $0.15/M
  {
    id: 'meta-llama/llama-4-maverick',
    name: 'Llama 4 Maverick',
    chef: 'Meta',
    chefSlug: 'meta',
    providers: ['openrouter'],
    free: false,
    context: '1M',
  },
  // Free models
  {
    id: 'google/gemini-2.5-flash-lite',
    name: 'Gemini 2.5 Flash Lite',
    chef: 'Google',
    chefSlug: 'google',
    providers: ['google'],
    free: true,
    context: '1M',
  },
  {
    id: 'openrouter/sherlock-think-alpha',
    name: 'Sherlock Think Alpha',
    chef: 'OpenRouter',
    chefSlug: 'openrouter',
    providers: ['openrouter'],
    free: true,
    context: '256K',
  },
  {
    id: 'tngtech/deepseek-r1t2-chimera:free',
    name: 'DeepSeek R1T2 Chimera',
    chef: 'TNG',
    chefSlug: 'tng',
    providers: ['tng'],
    free: true,
    context: '164K',
  },
  {
    id: 'z-ai/glm-4.5-air:free',
    name: 'GLM 4.5 Air',
    chef: 'Z.AI',
    chefSlug: 'z-ai',
    providers: ['z-ai'],
    free: true,
    context: '131K',
  },
  {
    id: 'tngtech/deepseek-r1t-chimera:free',
    name: 'DeepSeek R1T Chimera',
    chef: 'TNG',
    chefSlug: 'tng',
    providers: ['tng'],
    free: true,
    context: '164K',
  },
  // Premium - Frontier
  {
    id: 'anthropic/claude-sonnet-4.5',
    name: 'Claude Sonnet 4.5',
    chef: 'Anthropic',
    chefSlug: 'anthropic',
    providers: ['anthropic'],
    free: false,
    context: '1M',
  },
  {
    id: 'openai/gpt-5',
    name: 'GPT-5',
    chef: 'OpenAI',
    chefSlug: 'openai',
    providers: ['openai'],
    free: false,
    context: '400K',
  },
  {
    id: 'openai/o3-deep-research',
    name: 'o3 Deep Research',
    chef: 'OpenAI',
    chefSlug: 'openai',
    providers: ['openai'],
    free: false,
    context: '200K',
  },
  {
    id: 'google/gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    chef: 'Google',
    chefSlug: 'google',
    providers: ['google'],
    free: false,
    context: '1M',
  },
  {
    id: 'google/gemini-3-pro-preview',
    name: 'Gemini 3 Pro Preview',
    chef: 'Google',
    chefSlug: 'google',
    providers: ['google'],
    free: false,
    context: '2M',
  },
  {
    id: 'anthropic/claude-sonnet-4',
    name: 'Claude Sonnet 4',
    chef: 'Anthropic',
    chefSlug: 'anthropic',
    providers: ['anthropic'],
    free: false,
    context: '1M',
  },
  // Premium - Fast
  {
    id: 'x-ai/grok-code-fast-1',
    name: 'Grok Code Fast 1',
    chef: 'xAI',
    chefSlug: 'x-ai',
    providers: ['x-ai'],
    free: false,
    context: '256K',
  },
  {
    id: 'x-ai/grok-4-fast',
    name: 'Grok 4 Fast',
    chef: 'xAI',
    chefSlug: 'x-ai',
    providers: ['x-ai'],
    free: false,
    context: '2M',
  },
  {
    id: 'google/gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    chef: 'Google',
    chefSlug: 'google',
    providers: ['google'],
    free: false,
    context: '1M',
  },
  {
    id: 'google/gemini-2.0-flash-001',
    name: 'Gemini 2.0 Flash',
    chef: 'Google',
    chefSlug: 'google',
    providers: ['google'],
    free: false,
    context: '1M',
  },
  // Premium - Efficient
  {
    id: 'openai/gpt-5-mini',
    name: 'GPT-5 Mini',
    chef: 'OpenAI',
    chefSlug: 'openai',
    providers: ['openai'],
    free: false,
    context: '400K',
  },
  {
    id: 'anthropic/claude-haiku-4.5',
    name: 'Claude Haiku 4.5',
    chef: 'Anthropic',
    chefSlug: 'anthropic',
    providers: ['anthropic'],
    free: false,
    context: '200K',
  },
  {
    id: 'openai/gpt-4o-mini',
    name: 'GPT-4o Mini',
    chef: 'OpenAI',
    chefSlug: 'openai',
    providers: ['openai'],
    free: false,
    context: '128K',
  },
  {
    id: 'deepseek/deepseek-chat-v3.1',
    name: 'DeepSeek V3.1',
    chef: 'DeepSeek',
    chefSlug: 'deepseek',
    providers: ['deepseek'],
    free: false,
    context: '164K',
  },
  {
    id: 'meta-llama/llama-3.3-70b-instruct',
    name: 'Llama 3.3 70B',
    chef: 'Meta',
    chefSlug: 'meta',
    providers: ['meta'],
    free: false,
    context: '131K',
  },
]

export function canUseModel(model: Model, apiKey: string, serverHasKey: boolean): boolean {
  if (model.free) return true
  if (model.isClaudeCode) return true
  return !!apiKey || serverHasKey
}
