/**
 * src/worlds/donal-marketing.ts
 *
 * The first public ONE marketing team — 10 SEO/AI-ranking agents ingested
 * from Donal's operation-fury-plus repo, plus a CMO orchestrator.
 *
 * GENERATED by scripts/ingest-oo.ts. Hand-edit with care.
 *
 * Lifecycle:
 *   1. syncWorld(donalMarketing)   → TypeDB units + skills + capabilities
 *   2. wireWorld(donalMarketing)   → live runtime handlers via complete()
 *   3. seedAlliances()             → pre-drawn pheromone paths (strength=50)
 *   4. deployToAgentverse()        → npx agentlaunch deploy per agent
 *
 * Once synced, each agent runs on BOTH surfaces from the same markdown file:
 *   - ONE substrate (Telegram, web, substrate routing)
 *   - Agentverse (ASI:One discovery, FET payments)
 */

import type { WorldSpec } from '@/engine/agent-md'

export const donalMarketingAgents = [
  // CMO orchestrator — free, no price, routes briefs
  'cmo',

  // 10 priced skill agents from operation-fury-plus
    'ai-ranking',
    'citation',
    'forum',
    'full',
    'monthly',
    'niche-dir',
    'outreach',
    'quick',
    'schema',
    'social',
] as const

export const donalMarketing: WorldSpec = {
  name: 'marketing',
  description:
    'ONE marketing team — 11 agents covering AI visibility audits, citation ' +
    'building, outreach, schema, and reporting. Ingested from Donal operation-' +
    'fury-plus. Live on ONE substrate + Fetch.ai Agentverse, priced in FET.',
  agents: [], // populated at runtime by loading agents/donal/*.md
}

/**
 * Pre-drawn pheromone edges lifted from operation-fury-plus/alliances.yaml.
 * Each edge is cross-held at 50 FET between the two agents' tokens.
 *
 * Seeded as TypeDB path relations on first syncWorld() with strength=50.
 * Substrate learns from real traffic on top of these seeds — no cold start.
 */
export const donalMarketingAlliances = [
  { from: 'ai-ranking', to: 'citation', strength: 50, reason: 'flags gaps, fills them' },
  { from: 'citation', to: 'social', strength: 50, reason: 'NAP data feeds profile builder' },
  { from: 'citation', to: 'forum', strength: 50, reason: 'NAP data feeds outreach venues' },
  { from: 'citation', to: 'niche-dir', strength: 50, reason: 'batch sibling submissions' },
  { from: 'forum', to: 'outreach', strength: 50, reason: 'discovers venues, works them' },
  { from: 'outreach', to: 'quick', strength: 50, reason: 'feeds lead funnel' },
  { from: 'quick', to: 'full', strength: 50, reason: 'VSL hook upsells to full audit' },
  { from: 'ai-ranking', to: 'schema', strength: 50, reason: 'audit recommends schema gaps' },
  { from: 'full', to: 'schema', strength: 50, reason: 'audit recommends schema gaps' },
  { from: 'full', to: 'monthly', strength: 50, reason: 'full audit feeds retainer reports' },
  { from: 'monthly', to: 'schema', strength: 50, reason: 'monthly schema refreshes' },
]

export const ALLIANCE_STRENGTH = 50
