/**
 * TASK-PARSE — Deterministic parser for structured TODO files
 *
 * Reads TODO-{docname}.md files (generated by Haiku one-shot or hand-written).
 * Computes priority via pure arithmetic. No LLM in the loop.
 *
 * Format:
 *   - [ ] Task name here
 *     value: critical
 *     effort: low | medium | high
 *     phase: C1
 *     persona: ceo
 *     blocks: other-task-id, another-id
 *     exit: What "done" looks like
 *     tags: marketing, build, P0
 */

let _node: { readdir: any; readFile: any; join: any; basename: any } | null = null
async function node() {
  if (_node) return _node
  const fsp = await import('node:fs/promises')
  const path = await import('node:path')
  _node = { readdir: fsp.readdir, readFile: fsp.readFile, join: path.join, basename: path.basename }
  return _node
}

// ── Types ───────────────────────────────────────────────────────────────

export type Value = 'critical' | 'high' | 'medium' | 'low'
export type Phase = 'C1' | 'C2' | 'C3' | 'C4' | 'C5' | 'C6' | 'C7'
export type Effort = 'low' | 'medium' | 'high'
export type Wave = 'W1' | 'W2' | 'W3' | 'W4'

// Effort → model mapping: low=haiku, medium=sonnet, high=opus
export const EFFORT_MODEL: Record<Effort, string> = {
  low: 'haiku',
  medium: 'sonnet',
  high: 'opus',
}

// Wave → model mapping: W1=haiku (recon), W2=opus (decide), W3=sonnet (edit), W4=sonnet (verify)
export const WAVE_MODEL: Record<Wave, string> = {
  W1: 'haiku',
  W2: 'opus',
  W3: 'sonnet',
  W4: 'sonnet',
}

export interface Task {
  id: string
  name: string
  done: boolean
  value: Value
  effort: string
  wave: string
  phase: string
  persona: string
  context: string[]
  blocks: string[]
  exit: string
  tags: string[]
  source: string
  line: number
  priority: number
  formula: string
}

// ── Score Maps — Pure Arithmetic ────────────────────────────────────────

const VALUE_SCORES: Record<Value, number> = { critical: 30, high: 25, medium: 20, low: 10 }
const PHASE_SCORES: Partial<Record<Phase, number>> = { C1: 40, C2: 35, C3: 30, C4: 25, C5: 20, C6: 15, C7: 10 }
const PERSONA_SCORES: Record<string, number> = {
  ceo: 25,
  dev: 20,
  investor: 15,
  gamer: 15,
  kid: 10,
  freelancer: 10,
  agent: 5,
}

// ── Priority Formula ────────────────────────────────────────────────────

export function computePriority(
  value: Value,
  phase: string,
  persona: string,
  blockingCount: number,
): { score: number; formula: string } {
  const v = VALUE_SCORES[value] ?? 20
  const p = PHASE_SCORES[phase as Phase] ?? 25
  const per = PERSONA_SCORES[persona] ?? 5
  const b = Math.min(blockingCount * 5, 20)

  const score = v + p + per + b
  const parts = [`${value}=${v}`, `${phase}=${p}`, `${persona}=${per}`]
  if (b > 0) parts.push(`blocks(${blockingCount})=${b}`)
  const formula = parts.join(' + ')

  return { score, formula }
}

export function effectivePriority(score: number, strength: number, resistance: number, sensitivity = 0.7): number {
  return score + (strength - resistance) * sensitivity
}

// ── Slugify ─────────────────────────────────────────────────────────────

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60)
}

// ── Parser ──────────────────────────────────────────────────────────────

const CHECKBOX = /^- \[([ x])\] (.+)$/
const META = /^ {2}(\w[\w-]*):\s*(.+)$/

export function parseTodoFile(content: string, source: string): Task[] {
  const lines = content.split('\n')
  const tasks: Task[] = []
  let current: Partial<Task> | null = null
  let currentLine = 0

  const flush = () => {
    if (!current?.name) return
    const value = (current.value as Value) || 'medium'
    const effort = (current.effort as Effort) || 'medium'
    const wave = (current.wave as Wave) || 'W3'
    const phase = (current.phase as Phase) || 'C4'
    const persona = current.persona || 'agent'
    const context = current.context || []
    const blocks = current.blocks || []
    const { score, formula } = computePriority(value, phase, persona, blocks.length)

    tasks.push({
      id: current.id || slugify(current.name),
      name: current.name,
      done: current.done ?? false,
      value,
      effort,
      wave,
      phase,
      persona,
      context,
      blocks,
      exit: current.exit || '',
      tags: current.tags || [],
      source,
      line: currentLine,
      priority: score,
      formula,
    })
  }

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]

    const checkMatch = line.match(CHECKBOX)
    if (checkMatch) {
      flush()
      current = {
        done: checkMatch[1] === 'x',
        name: checkMatch[2].trim(),
      }
      currentLine = i + 1
      continue
    }

    if (current) {
      const metaMatch = line.match(META)
      if (metaMatch) {
        const [, key, val] = metaMatch
        switch (key) {
          case 'value':
            current.value = val.trim() as Value
            break
          case 'effort':
            current.effort = val.trim() as Effort
            break
          case 'wave':
            current.wave = val.trim() as Wave
            break
          case 'phase':
            current.phase = val.trim() as Phase
            break
          case 'persona':
            current.persona = val.trim()
            break
          case 'context':
            current.context = val
              .split(',')
              .map((s) => s.trim())
              .filter(Boolean)
            break
          case 'blocks':
            current.blocks = val
              .split(',')
              .map((s) => s.trim())
              .filter(Boolean)
            break
          case 'exit':
            current.exit = val.trim()
            break
          case 'tags':
            current.tags = val
              .split(',')
              .map((s) => s.trim())
              .filter(Boolean)
            break
          case 'id':
            current.id = val.trim()
            break
        }
      } else if (line.trim() === '' || line.startsWith('#')) {
        // blank line or heading ends the current item's metadata
      }
    }
  }
  flush()

  // Recompute priorities now that we know all blocking counts
  const blockCounts = new Map<string, number>()
  for (const t of tasks) {
    for (const _b of t.blocks) {
      blockCounts.set(t.id, (blockCounts.get(t.id) || 0) + 1)
    }
  }
  // A task's blocking score = how many OTHER tasks it blocks
  const blockerCounts = new Map<string, number>()
  for (const t of tasks) {
    for (const b of t.blocks) {
      blockerCounts.set(b, blockerCounts.get(b) || 0)
    }
  }
  // Count how many tasks list each ID in their blocks
  const blocksOthers = new Map<string, number>()
  for (const t of tasks) {
    for (const _dep of t.blocks) {
      // t blocks dep — meaning dep can't start until t is done
      // Actually: "blocks: X" means THIS task blocks X
      blocksOthers.set(t.id, (blocksOthers.get(t.id) || 0) + 1)
    }
  }

  for (const t of tasks) {
    const count = blocksOthers.get(t.id) || 0
    if (count > 0) {
      const { score, formula } = computePriority(t.value, t.phase, t.persona, count)
      t.priority = score
      t.formula = formula
    }
  }

  return tasks
}

// ── Scan all TODO-*.md files ────────────────────────────────────────────

export async function scanTodos(docsDir: string): Promise<Task[]> {
  const { readdir, readFile, join, basename } = await node()
  const entries = await readdir(docsDir).catch(() => [])
  const todoFiles = entries.filter(
    // template files are not real TODOs
    (f: string) => f.startsWith('TODO-') && f.endsWith('.md') && !/^TODO-template.*\.md$/.test(f),
  )

  const all: Task[] = []
  for (const file of todoFiles) {
    const content = await readFile(join(docsDir, file), 'utf-8')
    const source = basename(file, '.md').replace('TODO-', '')
    const tasks = parseTodoFile(content, source)
    all.push(...tasks)
  }

  // Deduplicate by id (first wins)
  const seen = new Set<string>()
  return all.filter((t) => {
    if (seen.has(t.id)) return false
    seen.add(t.id)
    return true
  })
}
