name = "one-sync"
main = "index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Sync every 5 minutes (free tier)
[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "KV"
id = "1c1dac4766e54a2c85425022a3b1e9da"

[vars]
APP_URL = "https://one.ie"
