import path from "path";
import { setupWeb } from "./setup-web.js";

export async function cloneWeb(orgProfile: {
  name: string;
  slug: string;
  domain: string;
}) {
  const targetDir = path.join(process.cwd(), "web");

  const envContent = `# ONE Platform Configuration
# Generated by CLI on ${new Date().toISOString()}

# Organization
PUBLIC_ORG_NAME="${orgProfile.name}"
PUBLIC_ORG_SLUG="${orgProfile.slug}"
PUBLIC_ORG_DOMAIN="${orgProfile.domain}"

# Convex Backend (update with your deployment)
PUBLIC_CONVEX_URL=https://your-deployment.convex.cloud
CONVEX_DEPLOYMENT=dev:your-deployment

# Better Auth
BETTER_AUTH_SECRET=
BETTER_AUTH_URL=http://localhost:4321

# OAuth (optional)
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
`;

  const result = await setupWeb({
    basePath: process.cwd(),
    webPath: targetDir,
    envContent,
  });

  if (result.alreadyExists) {
    console.log("⚠️  Web directory already exists, skipping clone");
    return { alreadyExists: true };
  }

  console.log("✓ Web template ready (from one-ie/one)");
  return { cloned: true };
}
