import { useCallback, useEffect, useRef, useState } from 'react'
import { Button } from '@/components/ui/button'
import { type DropdownGroup, type DropdownItem, dropdownGroups, findCannedAnswer } from '@/lib/chat/debby-dropdowns'
import { emitClick } from '@/lib/ui-signal'
import { cn } from '@/lib/utils'

const DEBBY_CLAW_URL = 'https://debby-claw.oneie.workers.dev'

const PLACEHOLDERS = [
  'Ask about learning English…',
  'Ask about pronunciation…',
  'Ask about our programs…',
  'Ask about live coaching…',
  'Ask about Amara, your AI tutor…',
]

type Message = { id: string; role: 'user' | 'assistant'; content: string; loading?: boolean; typing?: boolean }

function useTypingPlaceholder(phrases: string[], typingMs = 60, pauseMs = 2000) {
  const [text, setText] = useState('')
  const idx = useRef(0)
  const charIdx = useRef(0)
  const deleting = useRef(false)

  useEffect(() => {
    const tick = () => {
      const phrase = phrases[idx.current]
      if (!deleting.current) {
        charIdx.current++
        setText(phrase.slice(0, charIdx.current))
        if (charIdx.current >= phrase.length) {
          deleting.current = true
          return pauseMs
        }
      } else {
        charIdx.current--
        setText(phrase.slice(0, charIdx.current))
        if (charIdx.current <= 0) {
          deleting.current = false
          idx.current = (idx.current + 1) % phrases.length
        }
      }
      return deleting.current ? typingMs / 2 : typingMs
    }

    let timer: ReturnType<typeof setTimeout>
    const loop = () => {
      const delay = tick()
      timer = setTimeout(loop, delay)
    }
    timer = setTimeout(loop, typingMs)
    return () => clearTimeout(timer)
  }, [phrases, typingMs, pauseMs])

  return text
}

/** Auto-assign a persistent visitor ID — no name gate, collect details during conversation */
function useVisitorId() {
  const [groupId, setGroupId] = useState<string>('')

  useEffect(() => {
    const stored = localStorage.getItem('elevare-group')
    if (stored) {
      setGroupId(stored)
    } else {
      const gid = `web-${crypto.randomUUID().slice(0, 8)}`
      localStorage.setItem('elevare-group', gid)
      setGroupId(gid)
    }
  }, [])

  const resetGroupId = useCallback(() => {
    const gid = `web-${crypto.randomUUID().slice(0, 8)}`
    localStorage.setItem('elevare-group', gid)
    setGroupId(gid)
  }, [])

  return [groupId, resetGroupId] as const
}

export function DebbyChat() {
  const [groupId, resetGroupId] = useVisitorId()
  const [messages, setMessages] = useState<Message[]>([])
  const [input, setInput] = useState('')
  const [loading, setLoading] = useState(false)
  const [activeCategory, setActiveCategory] = useState<DropdownGroup['label'] | ''>('')
  const [latencyMs, setLatencyMs] = useState<number | null>(null)
  const taRef = useRef<HTMLTextAreaElement>(null)
  const bottomRef = useRef<HTMLDivElement>(null)
  const placeholder = useTypingPlaceholder(PLACEHOLDERS)

  const hasMessages = messages.length > 0
  const lastServerTs = useRef(0)

  const newChat = useCallback(() => {
    emitClick('ui:debby:new-chat')
    resetGroupId()
    setMessages([])
    setLatencyMs(null)
    lastServerTs.current = 0
  }, [resetGroupId])

  useEffect(() => {
    if (messages.length) bottomRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages.length])

  // Poll for new messages from server (admin replies, broadcasts)
  useEffect(() => {
    if (!groupId) return
    const poll = async () => {
      try {
        const res = await fetch(`${DEBBY_CLAW_URL}/messages/${encodeURIComponent(groupId)}`)
        if (!res.ok) return
        const data = await res.json()
        const serverMsgs = (data.messages || []) as {
          id: string
          sender: string
          content: string
          role: string
          ts: number
        }[]
        // Find assistant messages newer than our last known server timestamp
        // that weren't generated by this client session
        const newOnes = serverMsgs.filter((m) => m.role === 'assistant' && m.ts > lastServerTs.current)
        if (newOnes.length > 0) {
          lastServerTs.current = Math.max(...serverMsgs.map((m) => m.ts))
          setMessages((prev) => {
            // Only add messages whose IDs aren't already in local state
            const existingIds = new Set(prev.map((p) => p.id))
            const toAdd = newOnes
              .filter((m) => !existingIds.has(m.id))
              // Skip messages that match content we already have (from streaming)
              .filter((m) => !prev.some((p) => p.role === 'assistant' && p.content === m.content))
            if (toAdd.length === 0) return prev
            return [...prev, ...toAdd.map((m) => ({ id: m.id, role: 'assistant' as const, content: m.content }))]
          })
        } else if (serverMsgs.length > 0) {
          lastServerTs.current = Math.max(...serverMsgs.map((m) => m.ts))
        }
      } catch {}
    }
    // Initial sync — set the baseline timestamp
    poll()
    const id = setInterval(poll, 4000)
    return () => clearInterval(id)
  }, [groupId])

  /** Emit a substrate signal with tags — fire-and-forget to seed pheromone paths */
  const emitSignal = useCallback((receiver: string, tags: string[], content: string) => {
    fetch(`${DEBBY_CLAW_URL}/signal`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ sender: 'web:chat', receiver, data: { tags, weight: 1, content } }),
    }).catch(() => {})
  }, [])

  /** Sync Q+A to debby-claw D1 so LLM has context for follow-ups */
  const syncContext = useCallback(
    (question: string, answer: string) => {
      if (!groupId) return
      fetch(`${DEBBY_CLAW_URL}/message`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ group: groupId, text: question, prefill: answer }),
      }).catch(() => {})
    },
    [groupId],
  )

  /** Type out text character by character */
  const typeOut = useCallback((id: string, fullText: string) => {
    let i = 0
    const step = () => {
      i += 2 // 2 chars per frame for speed
      if (i >= fullText.length) {
        setMessages((prev) => prev.map((m) => (m.id === id ? { ...m, content: fullText, typing: false } : m)))
        return
      }
      setMessages((prev) => prev.map((m) => (m.id === id ? { ...m, content: fullText.slice(0, i) } : m)))
      requestAnimationFrame(step)
    }
    requestAnimationFrame(step)
  }, [])

  const send = useCallback(
    async (text: string) => {
      if (!text.trim() || loading) return
      const userId = crypto.randomUUID()
      const assistantId = crypto.randomUUID()

      // Check for pre-canned answer (instant, 0ms, no LLM cost)
      const canned = findCannedAnswer(text)

      setMessages((prev) => [
        ...prev,
        { id: userId, role: 'user', content: text },
        { id: assistantId, role: 'assistant', content: '', loading: !canned, typing: !!canned },
      ])
      setInput('')
      if (taRef.current) {
        taRef.current.style.height = 'auto'
        taRef.current.focus()
      }

      const t0 = performance.now()

      if (canned) {
        setLatencyMs(0)
        emitClick('ui:debby:canned', { type: 'text', content: `${canned.receiver}:${canned.tags.join(',')}` })
        emitSignal(canned.receiver, canned.tags, text)
        // Type out the answer with animation
        typeOut(assistantId, canned.answer)
        // Sync to debby-claw so LLM has context for follow-ups
        syncContext(text, canned.answer)
        return
      }

      // Live LLM call — streamed from Groq via debby-claw
      setLoading(true)
      emitClick('ui:debby:send', { type: 'text', content: text })

      try {
        const res = await fetch(`${DEBBY_CLAW_URL}/message`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ group: groupId, text, stream: true }),
        })

        if (!res.ok) throw new Error(`HTTP ${res.status}`)

        // Stream SSE chunks into the message
        const reader = res.body?.getReader()
        if (!reader) throw new Error('No stream')
        const decoder = new TextDecoder()
        let accumulated = ''
        let ttft = false

        setMessages((prev) => prev.map((m) => (m.id === assistantId ? { ...m, loading: false } : m)))

        let streamError = ''
        while (true) {
          const { done, value } = await reader.read()
          if (done) break
          const chunk = decoder.decode(value, { stream: true })
          for (const line of chunk.split('\n')) {
            if (!line.startsWith('data: ')) continue
            const payload = line.slice(6).trim()
            if (payload === '[DONE]') continue
            try {
              const parsed = JSON.parse(payload)
              if (parsed.error) {
                streamError = parsed.error
              } else if (parsed.t) {
                if (!ttft) {
                  ttft = true
                  setLatencyMs(Math.round(performance.now() - t0))
                }
                accumulated += parsed.t
                const content = accumulated
                setMessages((prev) => prev.map((m) => (m.id === assistantId ? { ...m, content } : m)))
              }
            } catch {}
          }
        }

        if (!accumulated) {
          const msg = streamError || 'No response'
          setMessages((prev) => prev.map((m) => (m.id === assistantId ? { ...m, content: msg } : m)))
        }
      } catch (err) {
        setMessages((prev) =>
          prev.map((m) =>
            m.id === assistantId ? { ...m, content: `Error: ${(err as Error).message}`, loading: false } : m,
          ),
        )
      } finally {
        setLoading(false)
      }
    },
    [loading, emitSignal, typeOut, syncContext, groupId],
  )

  const onPick = (label: DropdownGroup['label'], item: DropdownItem, index: number) => {
    emitClick('ui:debby:pick-question', { type: 'text', content: `${label}:${index}:${item.text}` })
    setActiveCategory('')
    send(item.text)
  }

  const onOpenDropdown = (label: DropdownGroup['label']) => {
    if (activeCategory === label) return
    setActiveCategory(label)
  }

  const activeGroup = dropdownGroups.find((g) => g.label === activeCategory)

  const inputDock = (
    <form
      className={cn('flex w-full', hasMessages && 'px-4 py-4')}
      onSubmit={(e) => {
        e.preventDefault()
        send(input)
      }}
    >
      <div className={cn('relative flex items-end w-full', hasMessages && 'max-w-2xl mx-auto')}>
        <textarea
          ref={taRef}
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onInput={(e) => {
            const t = e.currentTarget
            t.style.height = 'auto'
            t.style.height = `${Math.min(t.scrollHeight, 160)}px`
          }}
          onKeyDown={(e) => {
            if (e.key === 'Enter' && !e.shiftKey) {
              e.preventDefault()
              send(input)
            }
          }}
          placeholder={placeholder}
          rows={2}
          className={cn(
            'w-full resize-none rounded-2xl border border-border bg-card pl-4 pr-14 py-4 text-base leading-7 focus:outline-none focus:ring-2 focus:ring-ring/50',
            hasMessages ? 'min-h-[64px] max-h-[160px] overflow-y-auto' : 'min-h-[64px]',
          )}
        />
        <Button
          type="submit"
          disabled={!input.trim() || loading}
          className="absolute right-2 bottom-2 h-10 w-10 rounded-xl bg-accent text-accent-foreground hover:bg-accent/80 p-0 flex items-center justify-center"
        >
          {loading ? '…' : '⏎'}
        </Button>
      </div>
    </form>
  )

  const metaLine =
    latencyMs !== null ? (
      <div className="text-center text-xs uppercase tracking-[0.12em] text-muted-foreground">
        {latencyMs === 0 ? '0ms · instant' : `${latencyMs}ms`}
      </div>
    ) : null

  if (!hasMessages) {
    return (
      <div className="grid w-full min-h-[100svh] place-items-center px-4">
        <div className="max-w-2xl mx-auto w-full flex flex-col gap-6">
          <div className="text-center">
            <h1 className="text-2xl font-light tracking-tight text-foreground">Elevare</h1>
            <p className="text-sm text-muted-foreground mt-1">English coaching by Debby</p>
          </div>

          {inputDock}

          {metaLine}

          <div className="flex flex-col gap-4" onMouseLeave={() => setActiveCategory('')}>
            <div className="flex justify-center gap-2">
              {dropdownGroups.map((g) => (
                <button
                  key={g.label}
                  type="button"
                  onMouseEnter={() => onOpenDropdown(g.label)}
                  onClick={() => onOpenDropdown(g.label)}
                  className={cn(
                    'px-4 py-1.5 rounded-full text-xs uppercase tracking-[0.12em] transition-all',
                    activeCategory === g.label
                      ? 'bg-accent text-foreground scale-105'
                      : 'bg-muted text-muted-foreground hover:bg-accent/50 hover:text-foreground',
                  )}
                >
                  {g.label}
                </button>
              ))}
            </div>

            <div className="relative min-h-[180px]">
              {activeGroup && (
                <div className="flex flex-col gap-1 animate-in slide-in-from-top-4 fade-in duration-300">
                  {activeGroup.items.slice(0, 3).map((item, index) => (
                    <button
                      key={item.text}
                      type="button"
                      onClick={() => onPick(activeGroup.label, item, index)}
                      style={{ animationDelay: `${index * 40}ms` }}
                      className="text-center text-base leading-7 px-4 py-2 rounded-lg hover:bg-accent/50 transition-colors animate-in fade-in"
                    >
                      {item.text}
                    </button>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="flex flex-col h-screen bg-background text-foreground">
      <div className="flex items-center justify-between px-4 py-3 border-b border-border">
        <span className="text-sm text-muted-foreground">Elevare · Debby</span>
        <Button
          variant="ghost"
          size="sm"
          onClick={newChat}
          className="text-xs text-muted-foreground hover:text-foreground"
        >
          New Chat
        </Button>
      </div>
      <div className="flex-1 overflow-y-auto px-4 py-6">
        <div className="max-w-2xl mx-auto w-full space-y-4">
          {messages.map((m) => (
            <div key={m.id} className={`flex ${m.role === 'user' ? 'justify-end' : 'justify-start'}`}>
              <div
                className={cn(
                  'max-w-[80%] rounded-2xl px-4 py-3 text-base leading-7 whitespace-pre-wrap',
                  m.role === 'user' ? 'bg-primary text-primary-foreground' : 'bg-muted text-foreground',
                )}
              >
                {m.content}
                {(m.loading || m.typing) && (
                  <span className="inline-block w-1.5 h-3.5 ml-0.5 bg-current opacity-70 animate-pulse align-middle" />
                )}
              </div>
            </div>
          ))}
          <div ref={bottomRef} />
        </div>
      </div>

      {inputDock}

      <div className="py-2">{metaLine}</div>
    </div>
  )
}
