#!/usr/bin/env bun
/**
 * speed-check — compare fresh `.vitest/speed-report.md` vs tracked `one/speed-test.md`.
 *
 * Exit 0 when no benchmark regressed (no `✗ over` verdicts that weren't present
 * in the baseline). Exit 1 on regression — deploy W0 gate wires into this.
 *
 * The report format is generated by scripts/speed-report.ts. We parse the
 * markdown table rows and extract `<name>` + `<verdict>`. Only rows where
 * verdict is `over` count — `pass` and `pass (within Nx scale)` are green.
 *
 * Used by:
 *   - scripts/deploy.ts step 1.5 (after vitest, before build)
 *   - `bun run speed:check` (manual)
 */
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const ROOT = resolve(import.meta.dir, '..')
const FRESH = resolve(ROOT, '.vitest/speed-report.md')
const BASELINE = resolve(ROOT, 'one/speed-test.md')

interface BenchRow {
  name: string
  verdict: string
  p95: number | null
  budget: number | null
}

function parseReport(path: string): Map<string, BenchRow> {
  if (!existsSync(path)) return new Map()
  const md = readFileSync(path, 'utf8')
  const rows = new Map<string, BenchRow>()
  const lines = md.split('\n')
  for (const line of lines) {
    // Match: | `routing:select:100` | 0.005ms | 0.009 | 0.009 | 0.009 | 1 | ✓ pass | ... |
    const m = line.match(
      /^\|\s*`([^`]+)`\s*\|\s*([\d.]+)ms\s*\|\s*([\d.]+)\s*\|\s*([\d.]+)\s*\|\s*[\d.]+\s*\|\s*\d+\s*\|\s*[✓◐✗⊘]?\s*(pass(?:\s*\([^)]+\))?|over|missing)\b/,
    )
    if (!m) continue
    const [, name, budgetStr, , p95Str, verdictRaw] = m
    rows.set(name, {
      name,
      verdict: verdictRaw.trim().startsWith('pass') ? 'pass' : verdictRaw.trim(),
      p95: Number.parseFloat(p95Str),
      budget: Number.parseFloat(budgetStr),
    })
  }
  return rows
}

function main() {
  const fresh = parseReport(FRESH)
  const baseline = parseReport(BASELINE)

  if (fresh.size === 0) {
    console.log('⊘ No fresh report at .vitest/speed-report.md — run `bun run test` first.')
    process.exit(0)
  }

  const regressions: Array<{ name: string; fresh: BenchRow; baseline: BenchRow | null }> = []
  const recoveries: Array<{ name: string; fresh: BenchRow }> = []

  for (const [name, row] of fresh) {
    const prev = baseline.get(name) ?? null
    if (row.verdict === 'over') {
      if (!prev || prev.verdict !== 'over') {
        regressions.push({ name, fresh: row, baseline: prev })
      }
    } else if (prev?.verdict === 'over') {
      recoveries.push({ name, fresh: row })
    }
  }

  const freshOver = [...fresh.values()].filter((r) => r.verdict === 'over').length
  const baselineOver = [...baseline.values()].filter((r) => r.verdict === 'over').length

  console.log('── Speed Check ──')
  console.log(`  Baseline overs: ${baselineOver}`)
  console.log(`  Fresh overs:    ${freshOver}`)
  console.log(`  Regressions:    ${regressions.length}`)
  console.log(`  Recoveries:     ${recoveries.length}`)

  if (regressions.length > 0) {
    console.log('\n✗ Regressions:')
    for (const r of regressions) {
      const prevNote = r.baseline ? `was ${r.baseline.verdict} (p95 ${r.baseline.p95}ms)` : 'new benchmark'
      console.log(`  • ${r.name}: p95 ${r.fresh.p95}ms vs budget ${r.fresh.budget}ms  —  ${prevNote}`)
    }
  }
  if (recoveries.length > 0) {
    console.log('\n✓ Recoveries:')
    for (const r of recoveries) {
      console.log(`  • ${r.name}: p95 ${r.fresh.p95}ms ≤ budget ${r.fresh.budget}ms`)
    }
  }

  // Emit machine-readable summary for deploy.ts to forward to /api/signal
  const summary = {
    freshOver,
    baselineOver,
    regressions: regressions.map((r) => ({ name: r.name, p95: r.fresh.p95, budget: r.fresh.budget })),
    recoveries: recoveries.map((r) => ({ name: r.name, p95: r.fresh.p95 })),
  }
  if (process.env.SPEED_CHECK_JSON === '1') {
    console.log(`\n__SPEED_JSON__${JSON.stringify(summary)}`)
  }

  process.exit(regressions.length > 0 ? 1 : 0)
}

main()
